export enum SocketEvent {
	Connect = "connect",
	Disconnect = "disconnect",
	SendAuth = "auth",
	SendCreateAuth = "createAuth",
	ReceiveAuth = "receiveAuth",
	ReceiveFailedAuth = "receiveFailedAuth",
	DeleteSession = "deleteSession",
	DeletedSession = "deletedSession",
	PostAnswer = "postAnswer",
	ReceiveTaskProgressUpdate = "receiveTaskProgress",
	SendGiveConsent = "giveConsent",
	ReceiveGiveConsent = "receiveGiveConsent",
	Unpaired = "unpaired",
	Paired = "paired",
	Test = "test",
}
